### ISSUE TITLE
Why is this test_ Livelyspeaker_ The result of ted.py is not right, there is so much difference in FGD

### ISSUE THREAD

**Issue by Fengzixiao1** [zyhbili/LivelySpeaker#7]
I did not modify your code, and I followed your steps for testing, resulting in significantly different results. Is there anything to pay attention to，my result is
skip_steps 80
no_of_samples 31
guidance_param 1
beat_score 0.6347096964930564
motion_beats_sum 119788
beat_score_no_skip 0.6347096964930564
frechet_dist 13.280156134481217
diffusionstep 1000
eta 0
(13.280156134481217, 0.6347096964930564, 109.96293)
(13.280156134481217, 0.6347096964930564, 109.96293)

![1702002687958](https://github.com/zyhbili/LivelySpeaker/assets/132764927/dd7ba6c0-6b35-4629-916e-781244ac06fc)

**Comment by zyhbili** [comment]
Do you use the env of  ours i.e. conda create -n livelyspeaker python=3.7  and corresponding torch version in requirements.txt？ We also found a different env version would degrade the metric, perhaps due to the torch implementaion.

**Comment by zyhbili** [comment]
![result0](https://github.com/zyhbili/LivelySpeaker/assets/40693956/247ecf56-49e7-4bcb-a735-6750ab9ee8e1)
![result1](https://github.com/zyhbili/LivelySpeaker/assets/40693956/b26da393-3312-4a3f-9c22-2d2bb8e4be6f)
As shown above, I run my code again and obtain the same results as in the paper. Did you also get wrong results when running test_RAG_ted.py?

**Comment by Fengzixiao1** [comment]
This picture is the result of testing RAG，Why test_ Liverlyspeaker. py's FGD=10
![image](https://github.com/zyhbili/LivelySpeaker/assets/132764927/ca2b386b-a70e-41f4-aeac-4f3a69761712)

**Comment by zyhbili** [comment]
It also seems the results of test_RAG.py are slightly different from ours, probably due to the testing set or GPU difference? I obtain above results on RTX3090 and follow the origin dataset setting in TED. 
As depicted in paper, we propose a two-stage pipeline.  test_RAG.py evaluate the Rhythm-Aware Generator while  test_livelyspeaker.py evaluate the full pipeline i.e. SAG+RAG. And the quantitative results are exhibited in Table.1 (Ours Rhythm and Ours Full, respectively).

**Comment by Fengzixiao1** [comment]
Thank you for your answer

**Comment by Fengzixiao1** [comment]
I made a mistake，Thank you for your answer。
