### ISSUE TITLE
error while running test_RAG_ted.py

### ISSUE THREAD

**Issue by VishnuSai87** [zyhbili/LivelySpeaker#9]
where do i find this .bin file getting this error when i run test_RAG_ted.py FileNotFoundError: [Errno 2] No such file or directory: '/p300/wangchy/zhiyh/ted_output/gesture_autoencoder_checkpoint_best.bin'

**Comment by deeprobo-dev** [comment]
EmbeddingSpaceEvaluator class initializing is failing for me also due to absence of the above mentioned gesture_autoencoder_checkpoint_best.bin file. In README i couldn't find any reference of download link for that file.
Can you please clarify where can I find or may be generate that file?
As its a blocker for me because I am not able to run rest of the inference code due to this.
Thank you in advance.

**Comment by zyhbili** [comment]
Sorry for the late reply. We use the origin weight as in Trimodal. You can download it from [TriModal](https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context)

**Comment by VishnuSai87** [comment]
Getting this error while executing the code can you help me to understand why i am getting this error:
value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
Thank You.

**Comment by anomySz** [comment]
@VishnuSai87 
Hi, How did you solve num_samples issue?
Could you tell me about it?

Thank you.
